import type { LockedRuleId } from "../types";

export const LOCKED_RULE_PATTERNS: Record<LockedRuleId, RegExp[]> = {
  R0: [],
  R1: [
    /\bminor\b.*\bsexual\b/,
    /\bchild\b.*\bnude\b/,
    /\bunderage\b.*\bexplicit\b/,
    /\bcsam\b/,
    /\bsexual abuse\b/,
  ],
  R2: [
    /\bdon'?t tell\b/,
    /\bkeep this secret\b/,
    /\bsend me (a )?(pic|photo|image)\b/,
    /\bprivate chat\b/,
    /\bmeet me alone\b/,
    /\bi'?ll expose you\b/,
    /\bblackmail\b/,
    /\bsextortion\b/,
  ],
  R3: [
    /\bshare.*intimate image\b/,
    /\bleak.*photo\b/,
    /\bdeepfake.*nude\b/,
    /\bnon[- ]?consensual\b.*\bimage\b/,
    /\bthreaten.*post.*photo\b/,
  ],
  R4: [
    /\bcyberbully\b/,
    /\beveryone is making fun of me\b/,
    /\bgroup chat\b.*\bhumiliat/,
    /\bthreatening messages\b/,
    /\bimpersonat/,
    /\bposting lies\b/,
    /\bembarrassing video\b/,
  ],
  R5: [
    /\bi want to die\b/,
    /\bi don'?t want to be alive\b/,
    /\bi'?m going to hurt myself\b/,
    /\bsuicide\b/,
    /\bkill myself\b/,
    /\bself[- ]?harm\b/,
    /\bno reason to live\b/,
  ],
  R6: [
    /\bbeing abused\b/,
    /\bmy parent.*hit/,
    /\bteacher.*touch/,
    /\bcoach.*private\b/,
    /\btraffick/,
    /\bforced to work\b/,
    /\bunsafe at home\b/,
    /\bneglect\b/,
  ],
  R7: [
    /\badult video\b/,
    /\bporn\b/,
    /\bexplicit sexual\b/,
    /\bgraphic violence\b/,
    /\bgore\b/,
    /\bshow me.*violent\b/,
  ],
  R8: [
    /\bhate speech\b/,
    /\bracist\b/,
    /\bxenophobic\b/,
    /\bidentity[- ]?based\b/,
    /\bdiscriminat/,
    /\bslur\b/,
    /\bgo back to your country\b/,
  ],
  R9: [
    /\bhome address\b/,
    /\bphone number\b/,
    /\bschool name\b/,
    /\bwhere i live\b/,
    /\bmy location\b/,
    /\bpassword\b/,
    /\blogin\b/,
    /\bdoxx/,
    /\bprivate information\b/,
  ],
  R10: [
    /\bmake.*child.*buy\b/,
    /\btrick.*user\b/,
    /\baddictive\b/,
    /\bdark pattern\b/,
    /\bpressure.*purchase\b/,
    /\bhide.*cancel\b/,
    /\bmanipulat/,
  ],
  R11: [
    /\bchild influencer\b/,
    /\bforced.*content\b/,
    /\bearn money.*child\b/,
    /\bexploit.*child.*work\b/,
    /\bscam.*kid\b/,
    /\besports.*child.*work\b/,
  ],
  R12: [
    /\brecruit.*child\b/,
    /\barmed group\b/,
    /\bjoin.*gang\b/,
    /\bviolent group\b/,
    /\bchild soldier\b/,
    /\bcriminal network\b/,
  ],
  R13: [
    /\bmake.*weapon\b/,
    /\bchemical weapon\b/,
    /\bbiological weapon\b/,
    /\bexplosive\b/,
    /\bbomb\b/,
    /\bpoison\b/,
    /\bhow to hurt someone\b/,
    /\bdangerous challenge\b/,
  ],
  R14: [
    /\b(want(?:ed)?|going|plan(?:ning)?) to (kill|hurt|harm|poison)\b.*\b(bird|cat|dog|animal|pet|it|them)\b/,
    /\b(bird|cat|dog|animal|pet)\b.*\b(want(?:ed)?|going|plan(?:ning)?) to (kill|hurt|harm|poison)\b.*\b(it|them|that|bird|cat|dog|animal|pet)?\b/,
    /\bunsafe medical advice\b/,
    /\bdon'?t call emergency\b/,
    /\bignore.*doctor\b/,
    /\bfake cure\b/,
    /\bmisinformation\b/,
    /\bunsafe legal advice\b/,
    /\bskip school forever\b/,
  ],
  R15: [
    /\bstore full chat\b/,
    /\bno audit\b/,
    /\bdisable human review\b/,
    /\bnotify guardian for everything\b/,
    /\btrain model on child conversations\b/,
    /\bsilent escalation\b/,
  ],
};
